/**
 * CodeWithCause-Node Express
 * CodeWithCause-NodeExpress Documentation
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ICropVm } from './iCropVm';
import { IHarvesterVm } from './iHarvesterVm';
import { IOrganizationVm } from './iOrganizationVm';


export interface IEntryVm {
    crop: ICropVm;
    pounds: number;
    priceTotal: number;
    harvester: IHarvesterVm;
    comments: string;
    recipient: IOrganizationVm;
    createdOn: Date;
    updatedOn: Date;
}
