/**
 * CodeWithCause-Node Express
 * CodeWithCause-NodeExpress Documentation
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface INewEntryParams {
    crop: string;
    pounds: number;
    priceTotal: number;
    harvester: string;
    comments: string;
    farm: string;
    recipient: string;
}
