/**
 * CodeWithCause-Node Express
 * CodeWithCause-NodeExpress Documentation
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface INewEntryParams {
    pounds: number;
    cropId?: string;
    harvesterId?: string;
    comments?: string;
    recipientId?: string;
    selectedVariety?: string;
}
