/**
 * CodeWithCause-Node Express
 * CodeWithCause-NodeExpress Documentation
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type OrganizationType = 'Purchased' | 'Donated' | 'Internal';

export const OrganizationType = {
    Purchased: 'Purchased' as OrganizationType,
    Donated: 'Donated' as OrganizationType,
    Internal: 'Internal' as OrganizationType
}
